travis-ci: Do not make buildman warnings fatal
We currently will always see a number of warnings due to device tree
issues.  These (and other warnings) should not make the build be marked
as failure so catch exit status 129 specifically and return 0 in that
case.

Signed-off-by: Tom Rini <trini@konsulko.com>
Acked-by: Stephen Warren <swarren@nvidia.com>
Reviewed-by: Heiko Schocher <hs@denx.de>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -69,8 +69,15 @@ script:
  - if [[ "${TEST_CMD}" != "" ]]; then
      ${TEST_CMD};
    fi
+ # Exit code 129 means warnings only.
  - if [[ "${BUILDMAN}" != "" ]]; then
+     set +e;
      tools/buildman/buildman ${BUILDMAN};
+     if [[ "$?" == "0" || "$?" == "129" ]]; then
+       exit 0;
+     else
+       exit $?;
+     fi
    fi
 
 matrix:
